syntax = "proto3";

package g1;

message Pos {
  float x = 1;
  float y = 2;
  float z = 3;
}

message Euler {
  float x = 1;
  float y = 2;
  float z = 3;
}

message Quat {
  float x = 1;
  float y = 2;
  float z = 3;
  float w = 4;
}

message pnc_msg {
  float time = 1;

  Pos est_base_joint_pos = 2;
  Quat est_base_joint_ori = 3;

  repeated float joint_positions = 4;
  repeated float joint_velocities = 5;

  Pos lfoot_pos = 6;
  Pos rfoot_pos = 7;
  Quat lfoot_ori = 8;
  Quat rfoot_ori = 9;
  Pos lhand_pos = 10;
  Pos rhand_pos = 11;
  Quat lhand_ori = 12;
  Quat rhand_ori = 13;

  bool b_lfoot = 14;
  bool b_rfoot = 15;

  // mpc msg
  repeated Pos des_com_traj = 16;
  repeated Euler des_torso_ori_traj = 17;
  repeated Pos des_lf_pos_traj = 18;
  repeated Pos des_rf_pos_traj = 19;
  repeated Euler des_lf_ori_traj = 20;
  repeated Euler des_rf_ori_traj = 21;

  repeated float joint_pos_des = 22;
  repeated float joint_vel_des = 23;
  repeated float joint_trq_des = 24;

  // mpc costs
  uint32 total_iterations = 25;
  repeated float xreg_costs = 26;
  repeated float ureg_costs = 27;
  repeated float xbound_costs = 28;
  repeated float com_costs = 29;

  //mpc frame costs
  repeated float left_hand_frame_costs = 30;
  repeated float right_hand_frame_costs = 31;
  repeated float left_ankle_frame_costs = 32;
  repeated float right_ankle_frame_costs = 33;
  repeated float left_knee_frame_costs = 34;
  repeated float right_knee_frame_costs = 35;
  repeated float torso_link_frame_costs = 36;

  // mpc contact costs
  repeated float left_hand_contact_costs = 37;
  repeated float right_hand_contact_costs = 38;
  repeated float left_foot_contact_costs = 39;
  repeated float right_foot_contact_costs = 40;

  // current pos
  Pos torso_curr_pos = 41;
  Pos left_ankle_roll_curr_pos = 42;
  Pos right_ankle_roll_curr_pos = 43;
  Pos left_knee_curr_pos = 44;
  Pos right_knee_curr_pos = 45;
  Pos left_rubber_hand_curr_pos = 46;
  Pos right_rubber_hand_curr_pos = 47;
  Pos com_curr_pos = 48;
  Pos com_des_pos = 49;

  // MPC reaction force trajectories
  repeated Pos l_foot_rf = 50;
  repeated Pos r_foot_rf = 51;
  repeated Pos l_hand_rf = 52;
  repeated Pos r_hand_rf = 53;

  // MPC solver statistics
  bool b_fddp_feasible = 54;
  float solve_duration = 55;

  // MPC predicted frame positions
  repeated Pos predicted_torso = 56;
  repeated Pos predicted_lhand = 57;
  repeated Pos predicted_rhand = 58;
  repeated Pos predicted_lankle = 59;
  repeated Pos predicted_rankle = 60;
  repeated Pos predicted_lknee = 61;
  repeated Pos predicted_rknee = 62;

  // desired position of frames obtained from offline plan
  Pos torso_des_pos = 63;
  Pos left_ankle_roll_des_pos = 64;
  Pos right_ankle_roll_des_pos = 65;
  Pos left_knee_des_pos = 66;
  Pos right_knee_des_pos = 67;
  Pos left_rubber_hand_des_pos = 68;
  Pos right_rubber_hand_des_pos = 69;

  // Sensed contact forces
  Pos lf_contact_force = 70;
  Pos rf_contact_force = 71;
  Pos lh_contact_force = 72;
  Pos rh_contact_force = 73;

  bool b_lhand = 74;
  bool b_rhand = 75;

  // Torque limit boolean flags
  repeated bool b_trq_limit = 76;

}
