contact_frames:
  - l_foot_contact
  - r_foot_contact
  - left_rubber_hand
  - right_rubber_hand

joint_names:
  - base_pos_x
  - base_pos_y
  - base_pos_z
  - base_quat_x
  - base_quat_y
  - base_quat_z
  - base_quat_w
  - left_hip_pitch_joint
  - left_hip_roll_joint
  - left_hip_yaw_joint
  - left_knee_joint
  - left_ankle_pitch_joint
  - left_ankle_roll_joint
  - right_hip_pitch_joint
  - right_hip_roll_joint
  - right_hip_yaw_joint
  - right_knee_joint
  - right_ankle_pitch_joint
  - right_ankle_roll_joint
  - waist_yaw_joint
  - left_shoulder_pitch_joint
  - left_shoulder_roll_joint
  - left_shoulder_yaw_joint
  - left_elbow_joint
  - left_wrist_roll_joint
  - left_wrist_pitch_joint
  - left_wrist_yaw_joint
  - right_shoulder_pitch_joint
  - right_shoulder_roll_joint
  - right_shoulder_yaw_joint
  - right_elbow_joint
  - right_wrist_roll_joint
  - right_wrist_pitch_joint
  - right_wrist_yaw_joint

initial_config:
  base_pos_x: 0.
  base_pos_y: 0.
  base_pos_z: 0.68
  base_quat_x: 0.
  base_quat_y: 0.
  base_quat_z: 0.
  base_quat_w: 1.
  left_hip_pitch_joint: -0.697
  left_hip_roll_joint: 0.0
  left_hip_yaw_joint: 0.0
  left_knee_joint: 1.23
  left_ankle_pitch_joint: -0.53
  left_ankle_roll_joint: 0.0
  right_hip_pitch_joint: -0.697
  right_hip_roll_joint: 0.0
  right_hip_yaw_joint: 0.0
  right_knee_joint: 1.23
  right_ankle_pitch_joint: -0.53
  right_ankle_roll_joint: 0.0
  waist_yaw_joint: 0.0
  left_shoulder_pitch_joint: 0.0
  left_shoulder_roll_joint: 0.0
  left_shoulder_yaw_joint: 0.0
  left_elbow_joint: 0.0
  left_wrist_roll_joint: 0
  left_wrist_pitch_joint: 0
  left_wrist_yaw_joint: 0
  left_five_joint: 0
  left_six_joint: 0
  left_three_joint: 0.
  left_four_joint: 0.
  left_zero_joint: 0.
  left_one_joint: 0.
  left_two_joint: 0.
  right_shoulder_pitch_joint: 0.
  right_shoulder_roll_joint: 0.0 #-0.524
  right_shoulder_yaw_joint: 0.
  right_elbow_joint: 0.0 #1.571
  right_wrist_roll_joint: 0.
  right_wrist_pitch_joint: 0.
  right_wrist_yaw_joint: 0.
  right_five_joint: 0.
  right_six_joint: 0.
  right_three_joint: 0.
  right_four_joint: 0.
  right_zero_joint: 0.
  right_one_joint: 0.
  right_two_joint: 0.

#          [   Reg,   xBound,   CoM,    Frames,    Contacts    ]
cost_mask: [    1,      1,       1,        1,          1       ]

tracking_frames:
  - torso_primitive_shape
  - left_ankle_roll_link
  - right_ankle_roll_link
  - left_knee_link
  - right_knee_link
  - left_rubber_hand
  - right_rubber_hand

friction:
  w: 10000.0
  mu: 0.5

running_costs:
  xReg:
    w: 0.0001
    state_w:
      base_pos: [0.0, 0.0, 0.0]
      base_rot: [0.0, 0.0, 0.0]
      joint_pos: 0.0
      joint_vel: 100.0
  uReg:
    w: 0.02
  xBound:
    w: 0.001
  CoM:
    w: 10000.0
  tracking_frames:
    torso_primitive_shape: 
      pos: 1000.0
      rot: 0.0
    left_ankle_roll_link: 
      pos: 0.0
      rot: 1000.0
    right_ankle_roll_link: 
      pos: 0.0
      rot: 1000.0
    left_knee_link: 
      pos: 1000.0
      rot: 0.0
    right_knee_link: 
      pos: 1000.0
      rot: 0.0
    left_rubber_hand: 
      pos: 4000.0
      rot: 0.0
    right_rubber_hand: 
      pos: 4000.0
      rot: 0.0
  contact_frames:
    l_foot_contact:
      wt: 20.0
      wn: 50.0
    r_foot_contact:
      wt: 20.0
      wn: 50.0
    left_rubber_hand:
      wt: 20.0
      wn: 50.0
    right_rubber_hand:
      wt: 20.0
      wn: 50.0

terminal_costs:
  xReg:
    w: 0.01
    state_w:
      base_pos: [0.0, 0.0, 0.0]
      base_rot: [0.0, 0.0, 0.0]
      joint_pos: 0.0
      joint_vel: 20.0
  uReg:
    w: 0.01
  xBound:
    w: 300.0
  CoM:
    w: 3000.0
  tracking_frames:
    torso_primitive_shape:
      pos: 100.0
      rot: 0.0
    left_ankle_roll_link:
      pos: 10.0
      rot: 100.0
    right_ankle_roll_link:
      pos: 10.0
      rot: 100.0
    left_knee_link:
      pos: 1000.0
      rot: 0.0
    right_knee_link:
      pos: 1000.0
      rot: 0.0
    left_rubber_hand:
      pos: 100.0
      rot: 0.0
    right_rubber_hand:
      pos: 100.0
      rot: 0.0

mpc:
  dt: 0.025
  horizon: 4
  max_iter: 3