actuator_gains:
  left_hip_pitch_joint:
    kp: 650.0
    kd: 10.0
  left_hip_roll_joint:
    kp: 650.0
    kd: 10.0
  left_hip_yaw_joint:
    kp: 650.0
    kd: 10.0
  left_knee_joint:
    kp: 650.0
    kd: 10.0
  left_ankle_pitch_joint:
    kp: 650.0
    kd: 10.0
  left_ankle_roll_joint:
    kp: 650.0
    kd: 10.0
  right_hip_pitch_joint:
    kp: 650.0
    kd: 10.0
  right_hip_roll_joint:
    kp: 650.0
    kd: 10.0
  right_hip_yaw_joint:
    kp: 650.0
    kd: 10.0
  right_knee_joint:
    kp: 650.0
    kd: 10.0
  right_ankle_pitch_joint:
    kp: 650.0
    kd: 10.0
  right_ankle_roll_joint:
    kp: 650.0
    kd: 10.0
  waist_yaw_joint:
    kp: 50.0
    kd: 10.0
  left_shoulder_pitch_joint:
    kp: 50.0
    kd: 10.0
  left_shoulder_roll_joint:
    kp: 50.0
    kd: 10.0
  left_shoulder_yaw_joint:
    kp: 50.0
    kd: 10.0
  left_elbow_joint:
    kp: 50.0
    kd: 10.0
  left_wrist_roll_joint:
    kp: 50.0
    kd: 10.0
  left_wrist_pitch_joint:
    kp: 50.0
    kd: 10.0
  left_wrist_yaw_joint:
    kp: 50.0
    kd: 10.0
  right_shoulder_pitch_joint:
    kp: 50.0
    kd: 10.0
  right_shoulder_roll_joint:
    kp: 50.0
    kd: 10.0
  right_shoulder_yaw_joint:
    kp: 50.0
    kd: 10.0
  right_elbow_joint:
    kp: 50.0
    kd: 10.0
  right_wrist_roll_joint:
    kp: 50.0
    kd: 10.0
  right_wrist_pitch_joint:
    kp: 50.0
    kd: 10.0
  right_wrist_yaw_joint:
    kp: 50.0
    kd: 10.0

initial_config:
  base_pos_x: 0.
  base_pos_y: 0.
  base_pos_z: 0.68
  base_quat_x: 0.
  base_quat_y: 0.
  base_quat_z: 0.
  base_quat_w: 1.
  left_hip_pitch_joint: -0.697
  left_hip_roll_joint: 0.0
  left_hip_yaw_joint: 0.0
  left_knee_joint: 1.23
  left_ankle_pitch_joint: -0.53
  left_ankle_roll_joint: 0.0
  right_hip_pitch_joint: -0.697
  right_hip_roll_joint: 0.0
  right_hip_yaw_joint: 0.0
  right_knee_joint: 1.23
  right_ankle_pitch_joint: -0.53
  right_ankle_roll_joint: 0.0
  waist_yaw_joint: 0.0
  left_shoulder_pitch_joint: 0.0
  left_shoulder_roll_joint: 0.0
  left_shoulder_yaw_joint: 0.0
  left_elbow_joint: 0.0
  left_wrist_roll_joint: 0
  left_wrist_pitch_joint: 0
  left_wrist_yaw_joint: 0
  left_five_joint: 0
  left_six_joint: 0
  left_three_joint: 0.
  left_four_joint: 0.
  left_zero_joint: 0.
  left_one_joint: 0.
  left_two_joint: 0.
  right_shoulder_pitch_joint: 0.
  right_shoulder_roll_joint: 0.0
  right_shoulder_yaw_joint: 0.
  right_elbow_joint: 0.0
  right_wrist_roll_joint: 0.
  right_wrist_pitch_joint: 0.
  right_wrist_yaw_joint: 0.
  right_five_joint: 0.
  right_six_joint: 0.
  right_three_joint: 0.
  right_four_joint: 0.
  right_zero_joint: 0.
  right_one_joint: 0.
  right_two_joint: 0.

## Assumption [LF, RF, LH, RH] 
contact_sensor_frames:
  - left_ankle_roll_link
  - right_ankle_roll_link
  - left_wrist_yaw_link
  - right_wrist_yaw_link

mpc_dt: 0.0125